#!/bin/sh
# Aliases map simple commands to dot_* functions.

# Core
alias dotreload='dot_reload'
alias dotdoctor='dot_doctor'

# Editor
alias nvcfg='dot_nvimcfg'
alias nv="nvim"

# Arch Linux
alias pacmanupdate='arch_pacman_update'
alias paruupdate='arch_paru_update'
alias sysupdate='arch_sys_update'
